# Generated by Django 5.2.15 on 2026-06-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffinvite",
            name="role",
            field=models.CharField(
                choices=[
                    ("OWNER", "Owner"),
                    ("ADMIN", "Admin"),
                    ("MARKETING", "Marketing"),
                    ("DESIGNER", "Designer"),
                    ("SCANNER", "Scanner"),
                ],
                max_length=16,
            ),
        ),
    ]
