# Generated by Django 5.2.15 on 2026-07-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_staffinvite_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantsettings",
            name="enroll_headline",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="merchantsettings",
            name="enroll_tagline",
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
