# Generated by Django 5.2.15 on 2026-07-03 12:25

import branding.defaults
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0007_card_referral_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationTheme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template_key",
                    models.CharField(
                        choices=[
                            ("classic", "classic"),
                            ("hero", "hero"),
                            ("minimal", "minimal"),
                            ("bold", "bold"),
                        ],
                        default="classic",
                        max_length=16,
                    ),
                ),
                ("cover_image_url", models.URLField(blank=True)),
                (
                    "bg_color",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#(?:[0-9a-fA-F]{6})$", "Enter a hex color like #1A2B3C."
                            )
                        ],
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#(?:[0-9a-fA-F]{6})$", "Enter a hex color like #1A2B3C."
                            )
                        ],
                    ),
                ),
                (
                    "button_text_color",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#(?:[0-9a-fA-F]{6})$", "Enter a hex color like #1A2B3C."
                            )
                        ],
                    ),
                ),
                (
                    "font",
                    models.CharField(
                        choices=[("system", "system"), ("serif", "serif"), ("rounded", "rounded")],
                        default="system",
                        max_length=16,
                    ),
                ),
                ("welcome_body", models.TextField(blank=True, max_length=600)),
                (
                    "fields_config",
                    models.JSONField(default=branding.defaults.default_fields_config),
                ),
                ("qr_style", models.JSONField(default=branding.defaults.default_qr_style)),
                ("terms_url", models.URLField(blank=True)),
                ("privacy_url", models.URLField(blank=True)),
                ("hide_powered_by", models.BooleanField(default=True)),
                (
                    "card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enroll_themes",
                        to="core.card",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enroll_themes",
                        to="core.merchant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("card__isnull", True)),
                        fields=("merchant",),
                        name="uniq_merchant_default_theme",
                    ),
                    models.UniqueConstraint(
                        fields=("merchant", "card"), name="uniq_merchant_card_theme"
                    ),
                ],
            },
        ),
    ]
