# Generated by Django 5.2.15 on 2026-07-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationtheme',
            name='hide_powered_by',
        ),
    ]
