# Generated by Django 5.2.15 on 2026-06-29 09:23

import billing.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("FREE", "Free"),
                            ("STARTER", "Starter"),
                            ("GROWTH", "Growth"),
                            ("CHAIN", "Chain / Custom"),
                        ],
                        default="FREE",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TRIALING", "Trialing"),
                            ("ACTIVE", "Active"),
                            ("PAST_DUE", "Past due"),
                            ("CANCELED", "Canceled"),
                            ("LOCKED", "Locked"),
                        ],
                        default="TRIALING",
                        max_length=16,
                    ),
                ),
                (
                    "trial_ends_at",
                    models.DateTimeField(
                        blank=True, default=billing.models.default_trial_end, null=True
                    ),
                ),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("provider", models.CharField(blank=True, max_length=16)),
                ("gateway_ref", models.CharField(blank=True, max_length=128)),
                (
                    "merchant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="core.merchant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
