# Generated by Django 5.2.15 on 2026-07-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_subscription_cancel_at_period_end'),
        ('core', '0007_card_referral_enabled'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'issued_at'], name='billing_inv_status_2156f7_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status'], name='billing_sub_status_948046_idx'),
        ),
    ]
