# Generated by Django 5.2.15 on 2026-07-15 15:53

from django.db import migrations, models


def set_referral(apps, schema_editor):
    """Seed the new flag on existing rows from the hardcoded catalogue (Growth+)."""
    from billing.plans import PLAN_LIMITS

    Plan = apps.get_model("billing", "Plan")
    for key, limits in PLAN_LIMITS.items():
        Plan.objects.filter(key=str(key)).update(referral=bool(limits["referral"]))


def unset_referral(apps, schema_editor):
    apps.get_model("billing", "Plan").objects.update(referral=False)


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0013_remove_plan_whatsapp_remove_plan_whatsapp_quota"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="referral",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_referral, unset_referral),
    ]
