# Generated by Django 5.2.15 on 2026-07-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_subscription_gateway_billing_stopped'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='linking_transaction_ref',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pending_interval',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('annual', 'Annual')], max_length=8),
        ),
    ]
