# Generated by Django 5.2.15 on 2026-07-01 10:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(blank=True, max_length=120)),
                ("password", models.CharField(max_length=128)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SUPER_ADMIN", "Super Admin"),
                            ("FINANCE", "Finance"),
                            ("SUPPORT", "Support"),
                            ("MARKETING_ADMIN", "Marketing Admin"),
                            ("ENGINEERING", "Engineering"),
                            ("READ_ONLY", "Read Only"),
                        ],
                        default="READ_ONLY",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("mfa_secret", models.CharField(blank=True, max_length=64)),
                ("mfa_enabled", models.BooleanField(default=False)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="AdminAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("actor_email", models.EmailField(blank=True, max_length=254)),
                ("action", models.CharField(max_length=64)),
                ("target_type", models.CharField(blank=True, max_length=48)),
                ("target_id", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="console.adminuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="console_adm_created_2d1cbc_idx"),
                    models.Index(
                        fields=["actor", "-created_at"], name="console_adm_actor_i_46b662_idx"
                    ),
                    models.Index(
                        fields=["target_type", "target_id"], name="console_adm_target__8551a0_idx"
                    ),
                ],
            },
        ),
    ]
