# Generated by Django 5.2.15 on 2026-07-11 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0011_contactmessage_replied_at_and_more'),
        ('core', '0007_card_referral_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to='core.merchant'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='source',
            field=models.CharField(choices=[('marketing', 'Marketing site'), ('dashboard', 'Merchant dashboard')], default='marketing', max_length=16),
        ),
    ]
