# Generated by Django 5.2.15 on 2026-07-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0015_lead_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadactivity',
            name='kind',
            field=models.CharField(choices=[('lead_created', 'Lead Created'), ('website_form_submitted', 'Website Form Submitted'), ('manual_lead_created', 'Manual Lead Created'), ('phone_call_logged', 'Phone Call Logged'), ('whatsapp_sent', 'WhatsApp Sent'), ('email_sent', 'Email Sent'), ('priority_changed', 'Priority Changed'), ('status_changed', 'Status Changed'), ('assigned_sales_changed', 'Assigned Sales Changed'), ('demo_scheduled', 'Demo Scheduled'), ('demo_completed', 'Demo Completed'), ('proposal_sent', 'Proposal Sent'), ('converted_to_merchant', 'Converted To Merchant'), ('closed', 'Closed'), ('duplicate_merged', 'Duplicate Merged'), ('note_added', 'Note Added')], max_length=32),
        ),
    ]
