# Generated by Django 5.2.15 on 2026-07-01 11:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0001_initial"),
        ("core", "0007_card_referral_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantAdminMeta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("internal_notes", models.TextField(blank=True)),
                ("flags", models.JSONField(blank=True, default=dict)),
                (
                    "account_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_merchants",
                        to="console.adminuser",
                    ),
                ),
                (
                    "merchant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_meta",
                        to="core.merchant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
