# Generated by Django 5.2.15 on 2026-07-01 22:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_merchantadminmeta'),
        ('core', '0007_card_referral_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impersonation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_email', models.EmailField(blank=True, max_length=254)),
                ('target_email', models.EmailField(blank=True, max_length=254)),
                ('reason', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonations', to='console.adminuser')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonations', to='core.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_email', models.EmailField(blank=True, max_length=254)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_notes', to='console.adminuser')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_notes', to='core.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
