# Generated by Django 5.2.15 on 2026-07-02 07:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_impersonation_supportnote'),
        ('core', '0007_card_referral_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('card', 'Card'), ('merchant', 'Merchant')], max_length=16)),
                ('target_id', models.CharField(max_length=64)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('reason', models.CharField(max_length=200)),
                ('source', models.CharField(choices=[('heuristic', 'Heuristic scan'), ('report', 'Report')], default='heuristic', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('resolution_notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_flags', to='core.merchant')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_flags', to='console.adminuser')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('target_type', 'target_id', 'reason'), name='uniq_pending_content_flag')],
            },
        ),
    ]
