# Generated by Django 5.2.15 on 2026-07-02 13:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0004_contentflag'),
        ('core', '0007_card_referral_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('email', 'Email'), ('both', 'In-app + email')], default='in_app', max_length=8)),
                ('audience', models.CharField(choices=[('all', 'All merchants'), ('plan', 'By plan'), ('trial_ending', 'Trial ending'), ('at_risk', 'At-risk'), ('active', 'Recently active')], default='all', max_length=16)),
                ('audience_param', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent')], default='draft', max_length=12)),
                ('schedule_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipients', models.IntegerField(default=0)),
                ('emails_sent', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='console.adminuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='console.announcement')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_deliveries', to='core.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('announcement', 'merchant'), name='uniq_announcement_merchant')],
            },
        ),
    ]
