# Generated by Django 5.2.15 on 2026-07-03 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0005_announcement_announcementdelivery"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetentionPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("inactive_customer_days", models.IntegerField(default=0)),
                ("closed_merchant_days", models.IntegerField(default=0)),
                ("audit_log_days", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("updated_by_email", models.EmailField(blank=True, max_length=254)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="console.adminuser",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "retention policies",
            },
        ),
    ]
