# Generated by Django 5.2.15 on 2026-07-03 08:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0007_featureflag_platformsetting_featureflagoverride"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminuser",
            name="failed_login_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AdminSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("refresh_epoch", models.IntegerField(default=0)),
                ("user_agent", models.CharField(blank=True, max_length=256)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_auth_at", models.DateTimeField(blank=True, null=True)),
                ("revoked", models.BooleanField(default=False)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="console.adminuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["admin", "revoked", "-created_at"],
                        name="console_adm_admin_i_526685_idx",
                    )
                ],
            },
        ),
    ]
