# Generated by Django 5.2.15 on 2026-07-09 00:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0008_adminuser_failed_login_count_adminuser_locked_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('business_name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted')], default='new', max_length=16)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
