# Generated by Django 5.2.15 on 2026-07-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0010_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="replied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="status",
            field=models.CharField(
                choices=[("new", "New"), ("read", "Read"), ("replied", "Replied")],
                default="new",
                max_length=16,
            ),
        ),
    ]
