# Generated by Django 5.2.15 on 2026-07-17 12:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0012_contactmessage_merchant_contactmessage_source'),
        ('core', '0009_alter_merchant_plan_enterprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('status', 'Status'), ('priority', 'Priority'), ('temperature', 'Temperature'), ('source', 'Lead Source'), ('category', 'Business Category'), ('expected_plan', 'Expected Plan'), ('contact_method', 'Contact Method'), ('next_action', 'Next Action')], max_length=32)),
                ('slug', models.SlugField(max_length=64)),
                ('label', models.CharField(max_length=120)),
                ('color', models.CharField(blank=True, max_length=16)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['kind', 'order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('lead_created', 'Lead Created'), ('website_form_submitted', 'Website Form Submitted'), ('manual_lead_created', 'Manual Lead Created'), ('phone_call_logged', 'Phone Call Logged'), ('whatsapp_sent', 'WhatsApp Sent'), ('email_sent', 'Email Sent'), ('priority_changed', 'Priority Changed'), ('status_changed', 'Status Changed'), ('assigned_sales_changed', 'Assigned Sales Changed'), ('demo_scheduled', 'Demo Scheduled'), ('demo_completed', 'Demo Completed'), ('proposal_sent', 'Proposal Sent'), ('converted_to_merchant', 'Converted To Merchant'), ('closed', 'Closed'), ('note_added', 'Note Added')], max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('actor_label', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('called_at', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('result', models.CharField(choices=[('answered', 'Answered'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('phone_off', 'Phone Off'), ('wrong_number', 'Wrong Number'), ('reception_answered', 'Reception Answered'), ('manager_answered', 'Manager Answered'), ('owner_answered', 'Owner Answered'), ('call_back_later', 'Call Back Later'), ('not_interested', 'Not Interested')], max_length=32)),
                ('contact_method', models.CharField(choices=[('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('email', 'Email'), ('visit', 'Visit')], default='phone', max_length=32)),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('logged_by_label', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['-called_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='area',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_assigned', to='console.adminuser'),
        ),
        migrations.AddField(
            model_name='lead',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_method',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_leads', to='core.merchant'),
        ),
        migrations.AddField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_created', to='console.adminuser'),
        ),
        migrations.AddField(
            model_name='lead',
            name='created_by_type',
            field=models.CharField(choices=[('system', 'System'), ('sales_user', 'Sales User')], default='system', max_length=16),
        ),
        migrations.AddField(
            model_name='lead',
            name='expected_plan',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='lead',
            name='expected_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='facebook',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lead',
            name='instagram',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_activity',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_contact_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('website', 'Website'), ('manual', 'Manual')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_action',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_follow_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=16),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('google_maps', 'Google Maps'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('referral', 'Referral'), ('walk_in', 'Walk In'), ('manual', 'Manual'), ('other', 'Other')], default='manual', max_length=32),
        ),
        migrations.AddField(
            model_name='lead',
            name='temperature',
            field=models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], default='warm', max_length=16),
        ),
        migrations.AddField(
            model_name='lead',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('FINANCE', 'Finance'), ('SUPPORT', 'Support'), ('MARKETING_ADMIN', 'Marketing Admin'), ('ENGINEERING', 'Engineering'), ('SALES', 'Sales'), ('READ_ONLY', 'Read Only')], default='READ_ONLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new_lead', 'New Lead'), ('contact_attempted', 'Contact Attempted'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('phone_off', 'Phone Off'), ('wrong_number', 'Wrong Number'), ('reception_answered', 'Reception Answered'), ('manager_answered', 'Manager Answered'), ('owner_answered', 'Owner Answered'), ('interested', 'Interested'), ('very_interested', 'Very Interested'), ('hot_lead', 'Hot Lead'), ('demo_scheduled', 'Demo Scheduled'), ('demo_completed', 'Demo Completed'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('waiting_customer', 'Waiting Customer'), ('too_expensive', 'Too Expensive'), ('using_competitor', 'Using Competitor'), ('not_interested', 'Not Interested'), ('customer', 'Customer'), ('converted', 'Converted'), ('do_not_call_again', 'Do Not Call Again'), ('closed', 'Closed')], default='new_lead', max_length=32),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='console_lea_status_89f6c7_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lead_type'], name='console_lea_lead_ty_17621e_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_sales', 'status'], name='console_lea_assigne_19dd4c_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['next_follow_up_at'], name='console_lea_next_fo_456f2f_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone'], name='console_lea_phone_26e2ac_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email'], name='console_lea_email_b01c4c_idx'),
        ),
        migrations.AddIndex(
            model_name='crmchoice',
            index=models.Index(fields=['kind', 'is_active'], name='console_crm_kind_709cc2_idx'),
        ),
        migrations.AddConstraint(
            model_name='crmchoice',
            constraint=models.UniqueConstraint(fields=('kind', 'slug'), name='crmchoice_unique_kind_slug'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to='console.adminuser'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='console.lead'),
        ),
        migrations.AddField(
            model_name='leadcall',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='console.lead'),
        ),
        migrations.AddField(
            model_name='leadcall',
            name='logged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_calls', to='console.adminuser'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['lead', '-created_at'], name='console_lea_lead_id_4195e7_idx'),
        ),
        migrations.AddIndex(
            model_name='leadcall',
            index=models.Index(fields=['lead', '-called_at'], name='console_lea_lead_id_27b753_idx'),
        ),
    ]
