# Generated by Django 5.2.15 on 2026-07-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0014_crm_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
