# Generated by Django 5.2.15 on 2026-06-28 09:15

import core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('STAMP', 'Stamp card'), ('POINTS', 'Points card')], default='STAMP', max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('stamps_required', models.IntegerField()),
                ('reward_title', models.CharField(max_length=120)),
                ('reward_description', models.TextField(blank=True)),
                ('color_bg', models.CharField(blank=True, max_length=7)),
                ('color_fg', models.CharField(blank=True, max_length=7)),
                ('logo_url', models.URLField(blank=True)),
                ('google_class_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('legal_name', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=16)),
                ('plan', models.CharField(choices=[('FREE', 'Free'), ('STARTER', 'Starter'), ('GROWTH', 'Growth'), ('CHAIN', 'Chain / Custom')], default='FREE', max_length=16)),
                ('logo_url', models.URLField(blank=True)),
                ('color_bg', models.CharField(blank=True, max_length=7)),
                ('color_fg', models.CharField(blank=True, max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.merchant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnrollmentToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=32, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_tokens', to='core.card')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_tokens', to='core.merchant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=120)),
                ('stamp_count', models.IntegerField(default=0)),
                ('auth_token', models.CharField(default=core.models._generate_auth_token, max_length=48)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=16)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_cards', to='core.card')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_cards', to='core.merchant')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.merchant'),
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('threshold', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='core.card')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('SCANNER', 'Scanner')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='core.location')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='core.merchant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLAIMED', 'Claimed'), ('VOID', 'Void')], default='CLAIMED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='core.customercard')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='core.location')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='core.merchant')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='core.reward')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='core.staffuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StampLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('ENROLL', 'Enrollment'), ('STAMP', 'Stamp added'), ('REDEEM', 'Reward redeemed'), ('ADJUST', 'Manual adjustment')], max_length=16)),
                ('delta', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='core.customercard')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='core.location')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='core.merchant')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='core.staffuser')),
            ],
        ),
        migrations.CreateModel(
            name='WalletRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('APPLE', 'Apple Wallet'), ('GOOGLE', 'Google Wallet')], max_length=16)),
                ('device_library_id', models.CharField(blank=True, max_length=64)),
                ('push_token', models.CharField(blank=True, max_length=255)),
                ('google_object_id', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('customer_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_registrations', to='core.customercard')),
            ],
        ),
        migrations.AddConstraint(
            model_name='customercard',
            constraint=models.UniqueConstraint(fields=('card', 'customer_phone'), name='uniq_card_customer_phone'),
        ),
        migrations.AddIndex(
            model_name='stampledger',
            index=models.Index(fields=['customer_card', 'created_at'], name='core_stampl_custome_e83172_idx'),
        ),
        migrations.AddIndex(
            model_name='stampledger',
            index=models.Index(fields=['staff', 'created_at'], name='core_stampl_staff_i_ffd625_idx'),
        ),
        migrations.AddIndex(
            model_name='walletregistration',
            index=models.Index(fields=['customer_card', 'platform'], name='core_wallet_custome_b31ab7_idx'),
        ),
        migrations.AddIndex(
            model_name='walletregistration',
            index=models.Index(fields=['device_library_id'], name='core_wallet_device__25aa3e_idx'),
        ),
    ]
