# Generated by Django 5.2.15 on 2026-06-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_customercard_birthday"),
    ]

    operations = [
        migrations.AddField(
            model_name="customercard",
            name="customer_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
