# Generated by Django 5.2.15 on 2026-07-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_card_referral_enabled'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customercard',
            name='uniq_card_customer_phone',
        ),
        migrations.AlterField(
            model_name='customercard',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='customercard',
            constraint=models.UniqueConstraint(condition=models.Q(('customer_phone', ''), _negated=True), fields=('card', 'customer_phone'), name='uniq_card_customer_phone'),
        ),
    ]
