# Generated by Django 5.2.15 on 2026-06-29 20:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('core', '0004_card_hero_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='pending_plan',
            field=models.CharField(blank=True, choices=[('FREE', 'Free'), ('STARTER', 'Starter'), ('GROWTH', 'Growth'), ('CHAIN', 'Chain / Custom')], max_length=16),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_egp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pdf_url', models.URLField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=16)),
                ('gateway_ref', models.CharField(blank=True, max_length=128)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.merchant')),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['merchant', '-issued_at'], name='billing_inv_merchan_928ce9_idx')],
            },
        ),
    ]
