# Generated by Django 5.2.15 on 2026-06-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_subscription_pending_plan_invoice"),
        ("core", "0004_card_hero_image_url"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("gateway_ref", ""), _negated=True),
                fields=("provider", "gateway_ref"),
                name="uniq_invoice_provider_gateway_ref",
            ),
        ),
    ]
