# Generated by Django 5.2.15 on 2026-07-01 15:40

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_invoice_uniq_invoice_provider_gateway_ref"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=64)),
                (
                    "price_egp",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("archived", models.BooleanField(default=False)),
                ("max_cards", models.PositiveIntegerField(blank=True, null=True)),
                ("max_locations", models.PositiveIntegerField(blank=True, null=True)),
                ("max_staff", models.PositiveIntegerField(blank=True, null=True)),
                ("max_customers", models.PositiveIntegerField(blank=True, null=True)),
                ("whatsapp", models.BooleanField(default=False)),
                ("export", models.BooleanField(default=False)),
                ("api", models.BooleanField(default=False)),
                ("specialized_roles", models.BooleanField(default=False)),
                ("custom_branding", models.BooleanField(default=False)),
                ("automations", models.PositiveIntegerField(default=0)),
                (
                    "analytics",
                    models.CharField(
                        choices=[("basic", "Basic"), ("full", "Full")],
                        default="basic",
                        max_length=8,
                    ),
                ),
                ("whatsapp_quota", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["price_egp", "key"],
            },
        ),
    ]
