# Generated by Django 5.2.15 on 2026-07-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_seed_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="comp",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscription",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="override_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="override_plan",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FREE", "Free"),
                    ("STARTER", "Starter"),
                    ("GROWTH", "Growth"),
                    ("CHAIN", "Chain / Custom"),
                ],
                max_length=16,
            ),
        ),
    ]
