# Generated by Django 5.2.15 on 2026-07-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_subscription_admin_controls"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="note",
            field=models.TextField(blank=True),
        ),
    ]
