# Generated by Django 5.2.15 on 2026-07-02 14:28

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_invoice_note'),
        ('core', '0007_card_referral_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('type', models.CharField(choices=[('percent', 'Percent off'), ('fixed', 'Fixed EGP off'), ('free_months', 'Free months (comp)'), ('trial_extension', 'Trial extension (days)')], max_length=16)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_scope', models.JSONField(blank=True, default=list)),
                ('max_redemptions', models.IntegerField(blank=True, null=True)),
                ('per_merchant_once', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('redemption_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_egp', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('detail', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='billing.coupon')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to='core.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
