# Generated by Django 5.2.15 on 2026-07-03 07:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0008_coupon_couponredemption"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=16)),
                ("kind", models.CharField(blank=True, max_length=24)),
                ("gateway_ref", models.CharField(blank=True, max_length=128)),
                ("merchant_id_hint", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processed", "Processed"),
                            ("no_merchant", "No merchant matched"),
                            ("invalid", "Invalid signature"),
                            ("disabled", "Provider disabled"),
                            ("failed", "Processing failed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("error", models.CharField(blank=True, max_length=500)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "-created_at"], name="billing_web_provide_3dcfe8_idx"
                    ),
                    models.Index(
                        fields=["status", "-created_at"], name="billing_web_status_b25364_idx"
                    ),
                ],
            },
        ),
    ]
