# Generated by Django 5.2.15 on 2026-07-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0009_webhookdelivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="cancel_at_period_end",
            field=models.BooleanField(default=False),
        ),
    ]
