# Generated by Django 5.2.15 on 2026-07-11 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_coupongroup_coupon_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='whatsapp_quota',
        ),
    ]
