# Generated by Django 5.2.15 on 2026-07-16 19:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_reprice_and_drop_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='paymob_plan_id_annual',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='plan',
            name='paymob_plan_id_monthly',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_egp_annual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_interval',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=8),
        ),
        migrations.AddField(
            model_name='subscription',
            name='card_token_ref',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='subscription',
            name='card_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='paymob_subscription_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('PENDING_CARD', 'Pending card'), ('TRIALING', 'Trialing'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past due'), ('CANCELED', 'Canceled'), ('LOCKED', 'Locked')], default='TRIALING', max_length=24),
        ),
    ]
