# Generated by Django 5.2.15 on 2026-07-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_seed_annual_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='gateway_billing_stopped',
            field=models.BooleanField(default=False),
        ),
    ]
