# Generated by Django 5.2.15 on 2026-07-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_subscription_recurring_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='custom_features',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_campaigns_per_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='priority_support',
            field=models.BooleanField(default=False),
        ),
    ]
