# Generated by Django 5.2.15 on 2026-07-17 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_plan_enterprise_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='enterprise_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='override_plan',
            field=models.CharField(blank=True, choices=[('FREE', 'Free'), ('STARTER', 'Starter'), ('GROWTH', 'Growth'), ('CHAIN', 'Chain'), ('ENTERPRISE', 'Enterprise')], max_length=16),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='pending_plan',
            field=models.CharField(blank=True, choices=[('FREE', 'Free'), ('STARTER', 'Starter'), ('GROWTH', 'Growth'), ('CHAIN', 'Chain'), ('ENTERPRISE', 'Enterprise')], max_length=16),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Free'), ('STARTER', 'Starter'), ('GROWTH', 'Growth'), ('CHAIN', 'Chain'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=16),
        ),
    ]
