# Generated by Django 5.2.15 on 2026-07-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_merchantsettings_enroll_headline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantsettings",
            name="branches",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="merchantsettings",
            name="facebook_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="merchantsettings",
            name="instagram_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="merchantsettings",
            name="terms_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="merchantsettings",
            name="tiktok_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="merchantsettings",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
