# Generated by Django 5.2.15 on 2026-07-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leadgen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedlead",
            name="branch_count",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
