# Generated by Django 5.2.15 on 2026-07-22 14:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leadgen", "0002_generatedlead_branch_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiEnrichment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=64)),
                ("prompt_version", models.CharField(blank=True, max_length=16)),
                ("business_summary", models.TextField(blank=True)),
                ("target_customers", models.CharField(blank=True, max_length=500)),
                ("estimated_size", models.CharField(blank=True, max_length=64)),
                ("estimated_daily_visitors", models.PositiveIntegerField(blank=True, null=True)),
                ("estimated_monthly_customers", models.PositiveIntegerField(blank=True, null=True)),
                ("estimated_revenue_range", models.CharField(blank=True, max_length=120)),
                ("business_model", models.CharField(blank=True, max_length=64)),
                ("is_franchise", models.BooleanField(blank=True, null=True)),
                ("is_premium", models.BooleanField(blank=True, null=True)),
                ("estimated_branches", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("likelihood_uses_pos", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "likelihood_uses_loyalty",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "likelihood_accepts_digital",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("recommended_pitch", models.TextField(blank=True)),
                ("recommended_plan", models.CharField(blank=True, max_length=64)),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                        max_length=8,
                    ),
                ),
                ("confidence", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("tokens_in", models.PositiveIntegerField(default=0)),
                ("tokens_out", models.PositiveIntegerField(default=0)),
                ("cost_usd", models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("error", models.CharField(blank=True, max_length=500)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                (
                    "lead",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_enrichment",
                        to="leadgen.generatedlead",
                    ),
                ),
            ],
            options={
                "db_table": "lead_generation_ai",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"], name="lead_genera_status_0d5f11_idx"
                    ),
                    models.Index(fields=["lead"], name="lead_genera_lead_id_89ec17_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ApiUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google_places", "Google Places"),
                            ("google_geocoding", "Google Geocoding"),
                            ("glm", "Zhipu GLM"),
                            ("twilio_lookup", "Twilio Lookup"),
                            ("hunter", "Hunter.io"),
                        ],
                        max_length=24,
                    ),
                ),
                ("operation", models.CharField(max_length=64)),
                ("calls", models.PositiveIntegerField(default=1)),
                ("tokens_in", models.PositiveIntegerField(default=0)),
                ("tokens_out", models.PositiveIntegerField(default=0)),
                ("cost_usd", models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ("succeeded", models.BooleanField(default=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_usage",
                        to="leadgen.searchjob",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_usage",
                        to="leadgen.generatedlead",
                    ),
                ),
            ],
            options={
                "db_table": "lead_generation_api_usage",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "-created_at"], name="lead_genera_provide_36effd_idx"
                    ),
                    models.Index(fields=["job"], name="lead_genera_job_id_e8954f_idx"),
                    models.Index(fields=["-created_at"], name="lead_genera_created_7e4c2a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Verification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("phone", "Phone"), ("email", "Email")], max_length=8
                    ),
                ),
                ("target", models.CharField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("verified", "Verified"),
                            ("possible", "Possible"),
                            ("invalid", "Invalid"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("google_places", "Google Places"),
                            ("google_geocoding", "Google Geocoding"),
                            ("glm", "Zhipu GLM"),
                            ("twilio_lookup", "Twilio Lookup"),
                            ("hunter", "Hunter.io"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "line_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mobile", "Mobile"),
                            ("landline", "Landline"),
                            ("voip", "VoIP"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                ("carrier", models.CharField(blank=True, max_length=120)),
                ("deliverable", models.BooleanField(blank=True, null=True)),
                ("is_disposable", models.BooleanField(blank=True, null=True)),
                ("is_role_address", models.BooleanField(blank=True, null=True)),
                ("domain_valid", models.BooleanField(blank=True, null=True)),
                ("confidence", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("credits_used", models.PositiveIntegerField(default=0)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("error", models.CharField(blank=True, max_length=500)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="leadgen.generatedlead",
                    ),
                ),
            ],
            options={
                "db_table": "lead_generation_verification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"], name="lead_genera_status_e4e975_idx"
                    ),
                    models.Index(fields=["lead", "kind"], name="lead_genera_lead_id_1a4de2_idx"),
                    models.Index(fields=["result"], name="lead_genera_result_a430a0_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lead", "kind", "target"), name="uniq_leadgen_verification_target"
                    )
                ],
            },
        ),
    ]
