# Generated by Django 5.2.15 on 2026-06-30 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_card_hero_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("endpoint", models.CharField(max_length=32)),
                ("key", models.CharField(max_length=128)),
                ("response", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idempotency_records",
                        to="core.merchant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["created_at"], name="loyalty_ide_created_d6a045_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("merchant", "endpoint", "key"),
                        name="uniq_idem_merchant_endpoint_key",
                    )
                ],
            },
        ),
    ]
