# Generated by Django 5.2.15 on 2026-07-11 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automation',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='channel',
        ),
        migrations.DeleteModel(
            name='WhatsAppUsage',
        ),
    ]
