# Generated by Django 5.2.15 on 2026-07-03 07:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_card_referral_enabled"),
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletSyncFailure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        blank=True,
                        choices=[("APPLE", "Apple Wallet"), ("GOOGLE", "Google Wallet")],
                        max_length=16,
                    ),
                ),
                ("operation", models.CharField(max_length=32)),
                ("error", models.CharField(blank=True, max_length=500)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_failures",
                        to="core.customercard",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_sync_failures",
                        to="core.merchant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["resolved", "-created_at"], name="wallets_wal_resolve_732189_idx"
                    ),
                    models.Index(
                        fields=["merchant", "-created_at"], name="wallets_wal_merchan_fa61ca_idx"
                    ),
                ],
            },
        ),
    ]
