# Generated by Django 5.2.15 on 2026-07-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0005_walletcarddesign_strip_bg_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="walletcarddesign",
            name="google_stamp_hero",
            field=models.BooleanField(default=False),
        ),
    ]
