# Generated by Django 5.2.15 on 2026-07-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0009_walletcarddesign_stamp_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletcarddesign',
            name='apple_overlay',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='walletcarddesign',
            name='google_overlay',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='walletcarddesign',
            name='strip_bg_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='walletcarddesign',
            name='strip_stamps_visible',
            field=models.BooleanField(default=True),
        ),
    ]
