import { useEffect, useState } from 'react'
import { BellRing, Send, ShieldAlert } from 'lucide-react'
import { useOpsSettings, useSaveOpsSettings, useTestTelegram } from './api'

const DEFAULTS = { cpu_warning: 80, cpu_critical: 90, ram_warning: 80, ram_critical: 90, disk_warning: 80, disk_critical: 90, load_warning: 2, response_time_warning_ms: 500, error_rate_warning: 5, queue_size_warning: 100, failed_jobs_warning: 10 }
function Field({ label, name, value, onChange, suffix = '' }) { return <label className="block text-sm text-tx-2">{label}<div className="mt-1 flex overflow-hidden rounded-ctl border border-line bg-surface"><input type="number" min="0" name={name} value={value ?? ''} onChange={onChange} className="min-w-0 flex-1 bg-transparent px-3 py-2 text-tx outline-none" /><span className="px-3 py-2 text-tx-3">{suffix}</span></div></label> }

export default function Settings() {
  const { data, isLoading } = useOpsSettings(); const save = useSaveOpsSettings(); const test = useTestTelegram()
  const [form, setForm] = useState({ thresholds: DEFAULTS, notifications_enabled: false, hourly_reports_enabled: true, critical_alerts_enabled: true, warning_alerts_enabled: true, deployment_alerts_enabled: true, backup_alerts_enabled: true, ssl_alerts_enabled: true, quiet_hours_start: '', quiet_hours_end: '', telegram_chat_id: '', telegram_bot_token: '' })
  useEffect(() => { if (data) setForm((old) => ({ ...old, ...data, thresholds: { ...DEFAULTS, ...(data.thresholds || {}) }, telegram_bot_token: '' })) }, [data])
  const change = (e) => setForm((f) => ({ ...f, [e.target.name]: e.target.type === 'checkbox' ? e.target.checked : e.target.value }))
  const threshold = (e) => setForm((f) => ({ ...f, thresholds: { ...f.thresholds, [e.target.name]: Number(e.target.value) } }))
  const submit = (e) => { e.preventDefault(); save.mutate(form) }
  if (isLoading) return <div className="py-20 text-center text-tx-3">Loading settings…</div>
  return <form onSubmit={submit} className="mx-auto flex max-w-5xl flex-col gap-5"><section className="rounded-ctl border border-line bg-surface p-5"><div className="flex items-center gap-2"><BellRing size={18} className="text-brand" /><h2 className="font-semibold text-tx">Telegram notifications</h2></div><p className="mt-1 text-sm text-tx-3">The token is encrypted and is never shown again after saving.</p><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm text-tx-2">Bot token<input type="password" name="telegram_bot_token" value={form.telegram_bot_token} onChange={change} placeholder={data?.telegram_configured ? 'Configured — enter a new token to replace' : '123456:ABC…'} className="mt-1 w-full rounded-ctl border border-line bg-surface px-3 py-2 text-tx outline-none" /></label><label className="text-sm text-tx-2">Chat ID<input name="telegram_chat_id" value={form.telegram_chat_id || ''} onChange={change} className="mt-1 w-full rounded-ctl border border-line bg-surface px-3 py-2 text-tx outline-none" /></label></div><div className="mt-4 flex flex-wrap gap-4">{[['notifications_enabled','Enable notifications'],['hourly_reports_enabled','Hourly reports'],['critical_alerts_enabled','Critical alerts'],['warning_alerts_enabled','Warning alerts'],['deployment_alerts_enabled','Deployment alerts'],['backup_alerts_enabled','Backup alerts'],['ssl_alerts_enabled','SSL alerts']].map(([name,label]) => <label key={name} className="flex items-center gap-2 text-sm text-tx"><input type="checkbox" name={name} checked={Boolean(form[name])} onChange={change} />{label}</label>)}</div><button type="button" onClick={() => test.mutate()} disabled={test.isPending || !form.notifications_enabled} className="mt-4 inline-flex items-center gap-2 rounded-ctl border border-line px-3 py-2 text-sm text-tx hover:bg-surface-2"><Send size={15} />{test.isPending ? 'Sending…' : 'Send test notification'}</button>{test.isSuccess && <span className="ml-3 text-sm text-emerald-600">Test notification sent.</span>}{test.isError && <span className="ml-3 text-sm text-red-600">Could not send test notification.</span>}</section>
    <section className="rounded-ctl border border-line bg-surface p-5"><div className="flex items-center gap-2"><ShieldAlert size={18} className="text-brand" /><h2 className="font-semibold text-tx">Alert thresholds</h2></div><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="CPU warning" name="cpu_warning" value={form.thresholds.cpu_warning} onChange={threshold} suffix="%" /><Field label="CPU critical" name="cpu_critical" value={form.thresholds.cpu_critical} onChange={threshold} suffix="%" /><Field label="RAM warning" name="ram_warning" value={form.thresholds.ram_warning} onChange={threshold} suffix="%" /><Field label="RAM critical" name="ram_critical" value={form.thresholds.ram_critical} onChange={threshold} suffix="%" /><Field label="Disk warning" name="disk_warning" value={form.thresholds.disk_warning} onChange={threshold} suffix="%" /><Field label="Disk critical" name="disk_critical" value={form.thresholds.disk_critical} onChange={threshold} suffix="%" /><Field label="Load average warning" name="load_warning" value={form.thresholds.load_warning} onChange={threshold} /><Field label="Response time warning" name="response_time_warning_ms" value={form.thresholds.response_time_warning_ms} onChange={threshold} suffix="ms" /><Field label="Error rate warning" name="error_rate_warning" value={form.thresholds.error_rate_warning} onChange={threshold} suffix="%" /><Field label="Queue size warning" name="queue_size_warning" value={form.thresholds.queue_size_warning} onChange={threshold} /><Field label="Failed jobs warning" name="failed_jobs_warning" value={form.thresholds.failed_jobs_warning} onChange={threshold} /></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm text-tx-2">Quiet hours start<input type="time" name="quiet_hours_start" value={form.quiet_hours_start || ''} onChange={change} className="mt-1 block w-full rounded-ctl border border-line bg-surface px-3 py-2 text-tx" /></label><label className="text-sm text-tx-2">Quiet hours end<input type="time" name="quiet_hours_end" value={form.quiet_hours_end || ''} onChange={change} className="mt-1 block w-full rounded-ctl border border-line bg-surface px-3 py-2 text-tx" /></label></div><p className="mt-3 text-xs text-tx-3">Hourly reports pause during quiet hours. Critical alerts always send.</p></section><div className="flex justify-end"><button disabled={save.isPending} className="rounded-ctl bg-brand px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{save.isPending ? 'Saving…' : 'Save Stampn Ops settings'}</button></div>{save.isError && <p className="text-right text-sm text-red-600">Unable to save settings. Check every threshold and try again.</p>}</form>
}
