import { Activity, Box, Database, Gauge, RefreshCw, Server, Wifi } from 'lucide-react'
import MetricCard from './MetricCard'
import StatusBadge from './StatusBadge'
import { ago, bytes, pct } from './format'
import { useOpsDashboard, useRefreshOps } from './api'

const tone = (v, warning = 80, critical = 90) => v >= critical ? 'critical' : v >= warning ? 'warning' : 'healthy'

function Panel({ title, icon: Icon, children }) { return <section className="rounded-ctl border border-line bg-surface p-4"><div className="mb-4 flex items-center gap-2 font-semibold text-tx"><Icon size={17} className="text-brand" />{title}</div>{children}</section> }

export default function Dashboard() {
  const { data, isLoading, error } = useOpsDashboard(); const refresh = useRefreshOps()
  if (isLoading) return <div className="py-20 text-center text-tx-3">Loading live production status…</div>
  if (error) return <div className="rounded-ctl border border-red-500/30 bg-red-500/10 p-4 text-red-600">Unable to load Stampn Ops. Your session may not have Super Admin access.</div>
  const d = data || {}; const server = d.server || {}; const docker = d.docker || {}; const api = d.api || {}; const db = d.database || {}; const redis = d.redis || {}; const business = d.business || {}
  return <div className="flex flex-col gap-5">
    <section className="rounded-ctl border border-line bg-gradient-to-br from-brand/15 to-surface p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-tx-3">Production status</p><div className="mt-1 flex items-center gap-3"><strong className="text-4xl text-tx">{d.health_score ?? '—'}%</strong><StatusBadge value={d.status} /></div><p className="mt-2 text-sm text-tx-2">{d.environment || 'production'} · {d.location || 'unknown location'} · {d.version || 'version unavailable'}</p></div><button onClick={() => refresh.mutate()} disabled={refresh.isPending} className="inline-flex items-center gap-2 rounded-ctl border border-line bg-surface px-3 py-2 text-sm text-tx hover:bg-surface-2"><RefreshCw size={16} className={refresh.isPending ? 'animate-spin' : ''} />Refresh</button></div>
      {d.penalties?.length > 0 && <ul className="mt-4 space-y-1 text-sm text-amber-700 dark:text-amber-400">{d.penalties.map((p, i) => <li key={i}>• {p.reason}</li>)}</ul>}</section>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="CPU" value={pct(server.cpu_percent)} subtext={`load ${server.load_1 ?? '—'}`} progress={server.cpu_percent} tone={tone(server.cpu_percent)} /><MetricCard label="RAM" value={pct(server.ram_percent)} subtext={`${bytes(server.ram_used_bytes)} used`} progress={server.ram_percent} tone={tone(server.ram_percent)} /><MetricCard label="Disk" value={pct(server.disk_percent)} subtext={`${bytes(server.disk_free_bytes)} free`} progress={server.disk_percent} tone={tone(server.disk_percent)} /><MetricCard label="API response" value={api.response_time_ms ? `${api.response_time_ms} ms` : '—'} subtext={`${api.requests_per_minute ?? '—'} req/min`} /></div>
    <div className="grid gap-4 xl:grid-cols-2"><Panel title="Server" icon={Server}><dl className="grid grid-cols-2 gap-y-3 text-sm"><dt className="text-tx-3">Uptime</dt><dd className="text-right text-tx">{server.uptime_human || '—'}</dd><dt className="text-tx-3">Network upload</dt><dd className="text-right text-tx">{bytes(server.network_bytes_sent)}</dd><dt className="text-tx-3">Network download</dt><dd className="text-right text-tx">{bytes(server.network_bytes_received)}</dd><dt className="text-tx-3">Last deploy</dt><dd className="text-right text-tx">{ago(d.last_deploy_at)}</dd></dl></Panel><Panel title="Docker" icon={Box}><div className="mb-3 flex gap-2 text-sm"><span className="text-emerald-600">{docker.running ?? 0} running</span><span className="text-red-600">{docker.stopped ?? 0} stopped</span><span className="text-amber-600">{docker.restarting ?? 0} restarting</span></div><div className="max-h-48 space-y-2 overflow-auto">{(docker.containers || []).map((c) => <div key={c.id} className="flex items-center justify-between rounded bg-surface-2 px-3 py-2 text-sm"><span className="truncate text-tx">{c.name}</span><span className="flex items-center gap-3 text-tx-3">{pct(c.cpu_percent)} CPU · {pct(c.memory_percent)} RAM <StatusBadge value={c.health === 'healthy' ? 'healthy' : c.status} /></span></div>)}</div></Panel></div>
    <div className="grid gap-4 xl:grid-cols-3"><Panel title="Database" icon={Database}><p className="text-2xl font-bold text-tx">{db.connected ? 'Connected' : 'Unavailable'}</p><p className="mt-2 text-sm text-tx-3">{db.connections ?? '—'} connections · {bytes(db.size_bytes)}</p></Panel><Panel title="Redis & queues" icon={Wifi}><p className="text-2xl font-bold text-tx">{redis.connected ? 'Connected' : 'Unavailable'}</p><p className="mt-2 text-sm text-tx-3">{redis.keys ?? '—'} keys · {d.queues?.pending ?? '—'} pending jobs</p></Panel><Panel title="Business today" icon={Gauge}><p className="text-2xl font-bold text-tx">{business.online_users ?? '—'} online</p><p className="mt-2 text-sm text-tx-3">{business.active_businesses ?? '—'} active businesses · {business.stamps ?? '—'} stamps</p></Panel></div>
    <Panel title="Recent errors" icon={Activity}>{(d.recent_errors || []).length ? <div className="space-y-2">{d.recent_errors.map((e, i) => <div key={i} className="rounded bg-surface-2 p-3 text-sm"><span className="font-medium text-red-600">{e.source}</span><span className="ml-2 text-tx">{e.message}</span><span className="float-right text-tx-3">{ago(e.at)}</span></div>)}</div> : <p className="text-sm text-emerald-600">No recent errors reported.</p>}</Panel>
  </div>
}
