# Generated by Django 5.2.15 on 2026-07-22 13:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("console", "0016_lead_merge_activity"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedLead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("place_id", models.CharField(max_length=255)),
                ("business_name", models.CharField(max_length=255)),
                ("normalized_name", models.CharField(blank=True, max_length=255)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("phone_e164", models.CharField(blank=True, max_length=24)),
                ("website", models.URLField(blank=True, max_length=500)),
                ("website_domain", models.CharField(blank=True, max_length=253)),
                (
                    "rating",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
                ),
                ("reviews_count", models.PositiveIntegerField(default=0)),
                ("photos_count", models.PositiveIntegerField(default=0)),
                ("business_status", models.CharField(blank=True, max_length=32)),
                ("category", models.CharField(blank=True, max_length=64)),
                ("opening_hours", models.JSONField(blank=True, default=dict)),
                ("google_maps_url", models.URLField(blank=True, max_length=500)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("discovered", "Discovered"),
                            ("enriching", "Enriching"),
                            ("ready", "Ready for CRM"),
                            ("imported", "Imported"),
                            ("duplicate", "Duplicate"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                        ],
                        default="discovered",
                        max_length=16,
                    ),
                ),
                ("owner_name", models.CharField(blank=True, max_length=160)),
                (
                    "owner_name_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("manual", "Entered by rep"),
                            ("legal_page", "Privacy policy / terms"),
                            ("about_page", "About / team page"),
                            ("footer", "Website footer"),
                            ("review_response", "Signed Google review response"),
                            ("email_local_part", "Published email address"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "owner_name_confidence",
                    models.CharField(
                        blank=True,
                        choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                        max_length=8,
                    ),
                ),
                ("fit_score", models.PositiveSmallIntegerField(default=0)),
                (
                    "score_label",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hot", "Hot"),
                            ("warm", "Warm"),
                            ("cold", "Cold"),
                            ("ignore", "Ignore"),
                        ],
                        max_length=8,
                    ),
                ),
                ("score_breakdown", models.JSONField(blank=True, default=list)),
                (
                    "duplicate_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("place_id", "Same Google Place ID"),
                            ("phone", "Same phone number"),
                            ("website", "Same website domain"),
                            ("coordinates", "Same coordinates"),
                            ("similar_name", "Similar name at same location"),
                        ],
                        max_length=24,
                    ),
                ),
                ("crm_match_reason", models.CharField(blank=True, max_length=24)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                ("raw_places", models.JSONField(blank=True, default=dict)),
                (
                    "crm_match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leadgen_matches",
                        to="console.lead",
                    ),
                ),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="leadgen.generatedlead",
                    ),
                ),
                (
                    "imported_lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leadgen_origins",
                        to="console.lead",
                    ),
                ),
            ],
            options={
                "db_table": "lead_generation_leads",
                "ordering": ["-fit_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("country", models.CharField(max_length=2)),
                ("province", models.CharField(blank=True, max_length=120)),
                ("city", models.CharField(max_length=120)),
                ("street", models.CharField(blank=True, max_length=200)),
                ("radius_km", models.PositiveSmallIntegerField(default=5)),
                ("business_types", models.JSONField(default=list)),
                ("max_results", models.PositiveIntegerField(default=100)),
                ("center_lat", models.FloatField(blank=True, null=True)),
                ("center_lng", models.FloatField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("normal", "Normal"),
                            ("background", "Background"),
                        ],
                        default="normal",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("discovery", "Places Discovery"),
                            ("deduplication", "Deduplication"),
                            ("website_crawl", "Website Crawl"),
                            ("owner_resolution", "Owner Resolution"),
                            ("scoring", "Scoring"),
                            ("crm_match", "CRM Duplicate Check"),
                        ],
                        max_length=24,
                    ),
                ),
                ("discovered_count", models.PositiveIntegerField(default=0)),
                ("duplicate_count", models.PositiveIntegerField(default=0)),
                ("crawled_count", models.PositiveIntegerField(default=0)),
                ("ready_count", models.PositiveIntegerField(default=0)),
                ("imported_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=500)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leadgen_jobs",
                        to="console.adminuser",
                    ),
                ),
            ],
            options={
                "db_table": "lead_generation_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("discovery", "Places Discovery"),
                            ("deduplication", "Deduplication"),
                            ("website_crawl", "Website Crawl"),
                            ("owner_resolution", "Owner Resolution"),
                            ("scoring", "Scoring"),
                            ("crm_match", "CRM Duplicate Check"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("info", "Info"), ("warning", "Warning"), ("error", "Error")],
                        default="info",
                        max_length=8,
                    ),
                ),
                ("message", models.CharField(max_length=500)),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="leadgen.generatedlead",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="leadgen.searchjob",
                    ),
                ),
            ],
            options={
                "db_table": "lead_generation_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="generatedlead",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leads",
                to="leadgen.searchjob",
            ),
        ),
        migrations.CreateModel(
            name="SocialProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("tiktok", "TikTok"),
                            ("linkedin", "LinkedIn"),
                            ("whatsapp", "WhatsApp"),
                            ("youtube", "YouTube"),
                            ("x", "X"),
                        ],
                        max_length=16,
                    ),
                ),
                ("handle", models.CharField(blank=True, max_length=160)),
                ("url", models.URLField(max_length=500)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="socials",
                        to="leadgen.generatedlead",
                    ),
                ),
            ],
            options={
                "db_table": "lead_generation_social",
            },
        ),
        migrations.CreateModel(
            name="WebsiteProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                ("http_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=300)),
                ("pages_crawled", models.PositiveSmallIntegerField(default=0)),
                ("emails", models.JSONField(blank=True, default=list)),
                ("phones", models.JSONField(blank=True, default=list)),
                ("logo_url", models.URLField(blank=True, max_length=500)),
                ("meta_description", models.CharField(blank=True, max_length=500)),
                ("about_text", models.TextField(blank=True)),
                ("legal_entity", models.CharField(blank=True, max_length=255)),
                ("menu_urls", models.JSONField(blank=True, default=list)),
                ("reservation_platforms", models.JSONField(blank=True, default=list)),
                ("delivery_platforms", models.JSONField(blank=True, default=list)),
                ("technologies", models.JSONField(blank=True, default=list)),
                ("payment_providers", models.JSONField(blank=True, default=list)),
                ("pos_vendors", models.JSONField(blank=True, default=list)),
                ("loyalty_vendors", models.JSONField(blank=True, default=list)),
                (
                    "lead",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="website_profile",
                        to="leadgen.generatedlead",
                    ),
                ),
            ],
            options={
                "db_table": "lead_generation_website",
            },
        ),
        migrations.CreateModel(
            name="OwnerCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("role", models.CharField(blank=True, max_length=120)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Entered by rep"),
                            ("legal_page", "Privacy policy / terms"),
                            ("about_page", "About / team page"),
                            ("footer", "Website footer"),
                            ("review_response", "Signed Google review response"),
                            ("email_local_part", "Published email address"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                        max_length=8,
                    ),
                ),
                ("evidence_url", models.URLField(blank=True, max_length=500)),
                ("evidence_text", models.CharField(blank=True, max_length=500)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_candidates",
                        to="leadgen.generatedlead",
                    ),
                ),
            ],
            options={
                "db_table": "lead_generation_owner_candidates",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["lead"], name="lead_genera_lead_id_89b7ff_idx")],
            },
        ),
        migrations.AddIndex(
            model_name="searchjob",
            index=models.Index(
                fields=["status", "-created_at"], name="lead_genera_status_42e194_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchjob",
            index=models.Index(fields=["status", "priority"], name="lead_genera_status_b35ddf_idx"),
        ),
        migrations.AddIndex(
            model_name="searchjob",
            index=models.Index(fields=["created_by"], name="lead_genera_created_7cf54b_idx"),
        ),
        migrations.AddIndex(
            model_name="joblog",
            index=models.Index(fields=["job", "-created_at"], name="lead_genera_job_id_a0b776_idx"),
        ),
        migrations.AddIndex(
            model_name="joblog",
            index=models.Index(fields=["job", "level"], name="lead_genera_job_id_145c12_idx"),
        ),
        migrations.AddIndex(
            model_name="joblog",
            index=models.Index(fields=["lead"], name="lead_genera_lead_id_df3902_idx"),
        ),
        migrations.AddIndex(
            model_name="generatedlead",
            index=models.Index(fields=["job", "-fit_score"], name="lead_genera_job_id_fd4745_idx"),
        ),
        migrations.AddIndex(
            model_name="generatedlead",
            index=models.Index(fields=["job", "state"], name="lead_genera_job_id_cb4f6c_idx"),
        ),
        migrations.AddIndex(
            model_name="generatedlead",
            index=models.Index(fields=["job", "phone_e164"], name="lead_genera_job_id_f0ef93_idx"),
        ),
        migrations.AddIndex(
            model_name="generatedlead",
            index=models.Index(
                fields=["job", "website_domain"], name="lead_genera_job_id_2ccaf8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedlead",
            index=models.Index(
                fields=["job", "normalized_name"], name="lead_genera_job_id_5a306e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedlead",
            index=models.Index(fields=["place_id"], name="lead_genera_place_i_5a5bd1_idx"),
        ),
        migrations.AddIndex(
            model_name="generatedlead",
            index=models.Index(fields=["score_label"], name="lead_genera_score_l_b5564a_idx"),
        ),
        migrations.AddConstraint(
            model_name="generatedlead",
            constraint=models.UniqueConstraint(
                fields=("job", "place_id"), name="uniq_leadgen_lead_job_place"
            ),
        ),
        migrations.AddIndex(
            model_name="socialprofile",
            index=models.Index(fields=["lead", "platform"], name="lead_genera_lead_id_406ea7_idx"),
        ),
        migrations.AddConstraint(
            model_name="socialprofile",
            constraint=models.UniqueConstraint(
                fields=("lead", "platform"), name="uniq_leadgen_social_lead_platform"
            ),
        ),
    ]
