// Parity between this preview's geometry and the geometry the wallet passes are
// actually drawn with.
//
// `passGeometry.js` is a hand port of `backend/wallets/stamp_grid.py`. Nothing in
// either language stops them drifting, and a silent drift is the worst kind here:
// the merchant's preview keeps looking right while the pass on the customer's
// phone quietly does not match it.
//
// So both sides assert against one fixture generated by the Python
// implementation (`backend/tests/fixtures/stamp_geometry.json`). If someone
// changes the sizing on one side only, this file fails.

import { describe, it, expect } from 'vitest'
import fixture from '../../../../backend/tests/fixtures/stamp_geometry.json'
import { APPLE_STRIP, GOOGLE_HERO, STAMP_FILL, stampGeometry } from './passGeometry'

const SIZES = { apple: APPLE_STRIP, google: GOOGLE_HERO }

describe('passGeometry matches the backend renderer', () => {
  it('covers both canvases and every layout', () => {
    // A fixture that quietly lost its cases would make every test below vacuous.
    expect(fixture.cases.length).toBeGreaterThan(50)
    expect(new Set(fixture.cases.map((c) => c.size_name))).toEqual(
      new Set(['apple', 'google']),
    )
  })

  it.each(fixture.cases.map((c) => [`${c.size_name} ${c.layout} n=${c.n}`, c]))(
    'agrees on %s',
    (_label, expected) => {
      const actual = stampGeometry(expected.n, expected.layout, SIZES[expected.size_name])

      expect(actual.radius).toBe(expected.radius)
      expect(actual.ring).toBe(expected.ring)
      expect(actual.iconSize).toBe(expected.icon_size)
      expect(actual.pitch).toBeCloseTo(expected.pitch, 3)

      expect(actual.centers).toHaveLength(expected.centers.length)
      actual.centers.forEach((point, i) => {
        expect(point.x).toBeCloseTo(expected.centers[i].x, 3)
        expect(point.y).toBeCloseTo(expected.centers[i].y, 3)
      })
    },
  )

  it('shares the fill factor with the backend', () => {
    // Read off a case rather than hardcoded: radius is int(min(pitch,cellH) × fill),
    // so a changed factor on either side shows up here as well as in the cases.
    expect(STAMP_FILL).toBeLessThan(0.5)
    const oneStamp = fixture.cases.find(
      (c) => c.size_name === 'apple' && c.layout === 'grid' && c.n === 1,
    )
    expect(stampGeometry(1, 'grid', APPLE_STRIP).radius).toBe(oneStamp.radius)
  })
})
