# Generated by Django 5.2.15 on 2026-07-11 20:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_card_referral_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerProgramConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('partner_free_months', models.PositiveIntegerField(default=1)),
                ('merchant_free_months', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'partner program config',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('enabled_override', models.BooleanField(blank=True, null=True)),
                ('partner_free_months_override', models.PositiveIntegerField(blank=True, null=True)),
                ('merchant_free_months_override', models.PositiveIntegerField(blank=True, null=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to='core.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerReferral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributed_via', models.CharField(choices=[('signup_code', 'Signup code'), ('admin', 'Admin assignment')], max_length=16)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('reward_granted', models.BooleanField(default=False)),
                ('partner_months_granted', models.PositiveIntegerField(default=0)),
                ('merchant_months_granted', models.PositiveIntegerField(default=0)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='partners.partner')),
                ('referred_merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='core.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['partner', '-created_at'], name='partners_pa_partner_7caf58_idx')],
            },
        ),
    ]
