// Template registry — the single source of truth that maps a template id to its
// component, default theme, and a realistic sample payload. The gallery and any
// picker iterate this; nothing hardcodes template lists elsewhere.
import {
  LoyaltyPass,
  EventPass,
  BoardingPass,
  MembershipPass,
  CouponPass,
  GiftCardPass,
  InvitationPass,
  SpecialOccasionPass,
} from './templates'

export const TEMPLATES = [
  {
    id: 'loyalty',
    name: 'Loyalty',
    component: LoyaltyPass,
    theme: 'red',
    sample: {
      brand: 'Buns & Bros',
      offer: "4th Time's the Bite —",
      title: 'Free Burger!',
      customerName: 'Alex Rivera',
      memberId: 'BB-2048',
      qr: 'stampn:loyalty:BB-2048',
      rewardProgress: 3,
      rewardTarget: 5,
    },
  },
  {
    id: 'event',
    name: 'Event',
    component: EventPass,
    theme: 'black',
    sample: {
      brand: 'EDM Concert',
      label: 'Valid till',
      title: 'VIP Concert Access',
      date: '20/08/2024',
      venue: 'NYC, USA',
      barcodeValue: '739377923334',
      code: '739377923334',
      footerNote: 'Scan at entrance',
    },
  },
  {
    id: 'boarding',
    name: 'Boarding',
    component: BoardingPass,
    theme: 'yellow',
    sample: {
      brand: 'Spirit Airlines',
      route: 'SFO – LAX',
      passenger: 'John Doe',
      seat: '25B',
      gate: 'A4',
      flightNo: 'NK 812',
      boardingTime: '10:15 AM',
      date: '10/10/2025',
      qr: 'stampn:boarding:339295373239',
      code: '339295373239',
    },
  },
  {
    id: 'membership',
    name: 'Membership',
    component: MembershipPass,
    theme: 'brown',
    sample: {
      brand: 'Cafe Muse',
      tier: 'Gold',
      memberName: 'Sara Malik',
      memberId: 'CM-100294',
      expiry: '12/2026',
      barcodeValue: '739377923334',
      code: '739377923334',
    },
  },
  {
    id: 'coupon',
    name: 'Coupon',
    component: CouponPass,
    theme: 'orange',
    sample: {
      brand: 'Yum Donuts',
      offer: 'Your 5th visit =',
      discount: '30% OFF',
      expiry: 'Aug 30, 2025',
      validAt: 'In-store & online',
      barcodeValue: '739377923334',
      code: '739377923334',
    },
  },
  {
    id: 'giftcard',
    name: 'Gift Card',
    component: GiftCardPass,
    theme: 'purple',
    sample: {
      brand: 'Café Delights',
      balance: '$50.00',
      cardNumber: '•••• 3239',
      barcodeValue: 'stampn:gift:339295373239',
      code: '3392 9537 3239',
    },
  },
  {
    id: 'invitation',
    name: 'Invitation',
    component: InvitationPass,
    theme: 'yellow',
    sample: {
      title: "Ria's Birthday",
      guest: 'Amy Jones',
      time: '7:00 PM',
      date: 'April 10, 2025',
      location: '#7th Ave, Moore St. NYC',
      barcodeValue: '739377923334',
      code: '739377923334',
    },
  },
  {
    id: 'special',
    name: 'Special Occasion',
    component: SpecialOccasionPass,
    theme: 'pink',
    sample: {
      brand: 'Café Delights',
      holidayTitle: "Happy Mother's Day",
      offer: '20% OFF',
      validOn: 'May 11, 2025',
      validAt: 'In-store & online',
      qr: 'stampn:promo:739377923334',
      code: '739377923334',
    },
  },
]

export const TEMPLATE_BY_ID = Object.fromEntries(TEMPLATES.map((tpl) => [tpl.id, tpl]))
