# Generated by Django 5.2.15 on 2026-06-29 20:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_card_hero_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('PUSH', 'Push'), ('WHATSAPP', 'WhatsApp'), ('BOTH', 'Both')], max_length=16)),
                ('audience', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=16)),
                ('schedule_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered', models.IntegerField(default=0)),
                ('opened', models.IntegerField(default=0)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='core.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('reward_ready', 'Reward ready'), ('expiry', 'Expiry'), ('birthday', 'Birthday'), ('winback', 'Winback'), ('welcome', 'Welcome')], max_length=24)),
                ('enabled', models.BooleanField(default=False)),
                ('channel', models.CharField(choices=[('PUSH', 'Push'), ('WHATSAPP', 'WhatsApp'), ('BOTH', 'Both')], default='PUSH', max_length=16)),
                ('timing', models.CharField(blank=True, max_length=64)),
                ('template', models.TextField(blank=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='core.merchant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('merchant', 'key'), name='uniq_merchant_automation_key')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('sent', models.IntegerField(default=0)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_usage', to='core.merchant')),
            ],
            options={
                'indexes': [models.Index(fields=['merchant', 'period'], name='messaging_w_merchan_d39a8e_idx')],
                'constraints': [models.UniqueConstraint(fields=('merchant', 'period'), name='uniq_merchant_wa_period')],
            },
        ),
    ]
