# Generated by Django 5.2.15 on 2026-07-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_remove_automation_channel_remove_campaign_channel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automation",
            name="key",
            field=models.CharField(
                choices=[
                    ("reward_ready", "Reward ready"),
                    ("almost_there", "Almost there"),
                    ("expiry", "Expiry"),
                    ("birthday", "Birthday"),
                    ("winback", "Winback"),
                    ("welcome", "Welcome"),
                ],
                max_length=24,
            ),
        ),
    ]
