# Generated by Django 5.2.15 on 2026-06-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercard',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
