# Generated by Django 5.2.15 on 2026-06-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_customercard_customer_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="hero_image_url",
            field=models.URLField(blank=True),
        ),
    ]
