# Generated by Django 5.2.15 on 2026-06-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_staffuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="single_use",
            field=models.BooleanField(default=False),
        ),
    ]
