# Generated by Django 5.2.15 on 2026-07-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_card_single_use"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="referral_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
