# Generated by Django 5.2.15 on 2026-06-30 15:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_card_hero_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=120)),
                ("body", models.TextField()),
                (
                    "customer_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_messages",
                        to="core.customercard",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["customer_card", "-created_at"],
                        name="wallets_wal_custome_2abc95_idx",
                    )
                ],
            },
        ),
    ]
