# Generated by Django 5.2.15 on 2026-07-04 08:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_card_referral_enabled"),
        ("wallets", "0002_walletsyncfailure"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardShortCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=12, unique=True)),
                (
                    "customer_card",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="short_code",
                        to="core.customercard",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_short_codes",
                        to="core.merchant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["merchant", "code"], name="wallets_car_merchan_78d46c_idx")
                ],
            },
        ),
    ]
