# Generated by Django 5.2.15 on 2026-07-04 09:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_card_referral_enabled"),
        ("wallets", "0003_cardshortcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletCardDesign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label_color",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#(?:[0-9a-fA-F]{6})$", "Enter a hex color like #1A2B3C."
                            )
                        ],
                    ),
                ),
                ("apple_logo_text", models.CharField(blank=True, max_length=40)),
                ("apple_header", models.JSONField(blank=True, default=list)),
                ("apple_primary", models.JSONField(blank=True, default=list)),
                ("apple_secondary", models.JSONField(blank=True, default=list)),
                ("apple_auxiliary", models.JSONField(blank=True, default=list)),
                ("apple_back", models.JSONField(blank=True, default=list)),
                ("apple_strip_enabled", models.BooleanField(default=True)),
                ("strip_empty_url", models.URLField(blank=True)),
                ("strip_filled_url", models.URLField(blank=True)),
                ("google_title", models.CharField(blank=True, max_length=40)),
                ("google_subtitle", models.CharField(blank=True, max_length=60)),
                ("google_rows", models.JSONField(blank=True, default=list)),
                (
                    "card",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_design",
                        to="core.card",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_designs",
                        to="core.merchant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
