# Generated by Django 5.2.15 on 2026-07-05 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0007_walletcarddesign_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletcarddesign',
            name='stamp_color',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{6})$', 'Enter a hex color like #1A2B3C.')]),
        ),
        migrations.AddField(
            model_name='walletcarddesign',
            name='stamp_icon',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
