# Generated by Django 5.2.15 on 2026-07-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0008_walletcarddesign_stamp_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletcarddesign',
            name='stamp_layout',
            field=models.CharField(blank=True, choices=[('grid', 'grid'), ('columns', 'columns'), ('stagger', 'stagger')], max_length=12),
        ),
    ]
