# Generated by Django 5.2.15 on 2026-07-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0010_walletcarddesign_apple_overlay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletcarddesign',
            name='logo_scale',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='walletcarddesign',
            name='stamp_scale',
            field=models.FloatField(default=1.0),
        ),
    ]
